/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "rpc_server.h"

bool_t
xdr_RPCErrCode (XDR *xdrs, RPCErrCode *objp)
{
	register int32_t *buf;

	 if (!xdr_enum (xdrs, (enum_t *) objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_RetVal (XDR *xdrs, RetVal *objp)
{
	register int32_t *buf;

	 if (!xdr_RPCErrCode (xdrs, &objp->errcode))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->data, ~0))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_NameIdPair (XDR *xdrs, NameIdPair *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->voterid))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->name, ~0))
		 return FALSE;
	return TRUE;
}
